### ISSUE TITLE
order of enum constants is wrong

### ISSUE THREAD

**Issue by sakra** [jgaa/logfault#1]
The order of the `LogLevel` enum constants in line 108:

    enum class LogLevel { ERROR, WARN, INFO, NOTICE, DEBUG, TRACE };

does not match the order of the names in line 130:

    {{"ERROR", "WARNING", "NOTICE", "INFO", "DEBUG", "TRACE"}};

`INFO` and `NOTICE` is mixed up.

**Comment by jgaa** [comment]
Thanks
